# Generated by Django 4.0 on 2024-12-07 17:58

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import stdimage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientstatus_empresa_tipousuario_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_contratacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_suspension',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Suspension'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador de empresa'),
        ),
        migrations.AddField(
            model_name='planempresa',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='planempresa',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(default='images/users/avatar.png', force_min_size=False, upload_to='images/users/%Y/%m/', variations={'perfil': {'crop': True, 'height': 240, 'width': 240}, 'thumbnail': {'crop': True, 'height': 45, 'width': 45}}, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.TextField(blank=True, max_length=100, verbose_name='Dirección de facturación'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de facturación'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ciudad/Municipio'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='Localidad/Barrio/Departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, max_length=35, verbose_name='Licencia DNI/C.I./C.C.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(message='Ingrese solo números.', regex='^\\d+$')], verbose_name='Teléfono Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
